spring.application.name=servicenow-integration

# Adapter API base URL and timeouts
adapter.base-url=http://localhost:8081
adapter.connect-timeout-ms=2000
adapter.read-timeout-ms=5000

# Disable DB auto-configuration (this service does not use a DB yet)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Server config (optional)
server.port=8080

# Jackson: accept empty string ("") as null for object fields (e.g., LinkValueDTO)
spring.jackson.deserialization.ACCEPT_EMPTY_STRING_AS_NULL_OBJECT=true

# SAP adapter configuration (bound to SAPApiProperties)
sap.api.base-url=http://localhost:8088
sap.api.auth-token=
sap.api.onboarding-candidate-endpoint=/api/service_now/onboarding_candidate_info/

# ServiceNow configuration
servicenow.api.instance-base-url=https://dev313338.service-now.com